# Generated by Django 4.2.7 on 2024-01-01 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_data',
            fields=[
                ('Customer_ID', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(max_length=30)),
                ('Customer_Contact', models.CharField(max_length=12)),
                ('Company_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Network_Services',
            fields=[
                ('Service_ID', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('Service_Name', models.CharField(max_length=256)),
                ('Port_Number', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability_Data',
            fields=[
                ('Vuln_ID', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('Vuln_Name', models.CharField(max_length=256)),
                ('Vuln_Desc', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Device_Data',
            fields=[
                ('Device_ID', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('IP_Address', models.GenericIPAddressField()),
                ('MAC_Address', models.CharField(max_length=20)),
                ('Operating_Sytem', models.CharField(max_length=256)),
                ('created_on', models.DateTimeField(auto_now=True, help_text='Time and date this was created')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Time and date this was updated')),
                ('customer_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer_data')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
