# Generated by Django 4.2.7 on 2024-01-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Data',
            fields=[
                ('Device_ID', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('IP_Address', models.GenericIPAddressField()),
                ('Port', models.IntegerField(null=True)),
                ('Service', models.CharField(max_length=256, null=True)),
                ('Operating_Sytem', models.CharField(max_length=256)),
                ('created_on', models.DateTimeField(auto_now=True, help_text='Time and date this was created')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Time and date this was updated')),
                ('MAC_Address', models.CharField(max_length=256)),
            ],
        ),
    ]
