# Generated by Django 4.2.7 on 2024-01-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_data',
            name='Port',
        ),
        migrations.RemoveField(
            model_name='device_data',
            name='Service',
        ),
        migrations.AddField(
            model_name='device_data',
            name='Hardware_Details',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
