# Generated by Django 4.2.7 on 2024-01-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='port',
            old_name='Reason',
            new_name='reason',
        ),
    ]
