# Generated by Django 4.2.7 on 2024-01-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_network_services_delete_vulnerability_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_data',
            name='MAC_Address',
        ),
        migrations.AddField(
            model_name='device_data',
            name='Port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device_data',
            name='Service',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device_data',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Time and date this was updated'),
        ),
    ]
