# Generated by Django 4.2.7 on 2024-01-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_device_data_port_remove_device_data_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_data',
            name='Hardware_Details',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
