# Generated by Django 4.2.7 on 2024-01-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_device_data_mac_address_device_data_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_data',
            name='Mac_Address',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device_data',
            name='Port',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='device_data',
            name='Service',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='device_data',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, help_text='Time and date this was created', null=True),
        ),
        migrations.AlterField(
            model_name='device_data',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Time and date this was updated', null=True),
        ),
    ]
