# Generated by Django 4.2.7 on 2024-01-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_device_data_mac_address_alter_device_data_port_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_data',
            old_name='Mac_Address',
            new_name='MAC_Address',
        ),
    ]
