# Generated by Django 4.2.7 on 2024-01-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_mac_address_device_data_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_data',
            name='created_on',
            field=models.DateTimeField(auto_now=True, help_text='Time and date this was created'),
        ),
        migrations.AlterField(
            model_name='device_data',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, help_text='Time and date this was updated'),
        ),
    ]
