# models.py
#Resources used: https://docs.djangoproject.com/en/5.0/topics/db/models/
from django.db import models

#Models used for the SQLWorkbench Database.
#id fields are automatically generated by Django so are not written here.

class Customer_Data(models.Model):
    company_name = models.CharField(max_length=256)
    location = models.CharField(max_length=256)
    contact_name = models.CharField(max_length=256)
    contact_position = models.CharField(max_length=256)
    contact_number = models.CharField(max_length=256)
    initial_ip_range = models.CharField(max_length=256)

    def __str__(self):
        return self.company_name

class OS_Info(models.Model):

    type = models.CharField(max_length=256)
    vendor = models.CharField(max_length=256)
    osfamily = models.CharField(max_length=256)
    osgen = models.CharField(max_length=256)
    accuracy = models.CharField(max_length=256)


class Device_Data(models.Model):

    IP_Address = models.GenericIPAddressField()
    Operating_System = models.OneToOneField(OS_Info, on_delete=models.CASCADE, null=True, blank=True)
    created_on = models.DateTimeField(auto_now=True, help_text="Time and date this was created")
    updated_on = models.DateTimeField(auto_now=True, help_text="Time and date this was updated")
    MAC_Address = models.CharField(max_length=256)
    Hardware_Details = models.CharField(max_length=256, null=True, blank=True)
    customer_data = models.ForeignKey(Customer_Data, on_delete=models.CASCADE, related_name='customers', null = True, blank = True)

    def __str__(self):
        return self.IP_Address
    

class Port(models.Model):
    protocol = models.CharField(max_length = 256)
    portid = models.PositiveSmallIntegerField()
    reason = models.CharField(max_length = 256)
    reason_ttl = models.CharField(max_length = 256)
    device_data = models.ForeignKey(Device_Data, on_delete=models.CASCADE, related_name='ports')

class Netsweeper_Result(models.Model):
    ip_address = models.CharField(max_length = 256)
    mac_address = models.CharField(max_length = 256)
    hostname = models.CharField(max_length = 256)
    vendor = models.CharField(max_length = 256)
    state = models.CharField(max_length = 256)
    customer_data = models.ForeignKey(Customer_Data, on_delete=models.CASCADE, related_name='netsweeper_customers', null = True, blank = True)
